name: NASA Project CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use Node.js version 16
        uses: actions/setup-node@v2
        runs:
          using: "node16"
      - run: npm install
      - run: npm run build --prefix client
